import { Download, RefreshCw, Link, Tag } from 'lucide-react';
import AEOScoreCard from './AEOScoreCard.jsx';
import SchemaCard from './SchemaCard.jsx';

const PAGE_TYPE_LABELS = {
  article: { label: 'Article / Blog',           emoji: '📝' },
  faq:     { label: 'FAQ Page',                 emoji: '❓' },
  news:    { label: 'News & Media',             emoji: '📰' },
  contact: { label: 'Contact Us',               emoji: '📞' },
  bod:     { label: 'Board of Directors (BOD)', emoji: '👥' },
  homepage:{ label: 'Homepage',                 emoji: '🏠' },
  generic: { label: 'Generic Page',             emoji: '🌐' },
};

export default function ResultsPanel({ results, onReset }) {
  const { schemas, score, meta, pageType } = results;
  const pageTypeInfo = PAGE_TYPE_LABELS[pageType] || PAGE_TYPE_LABELS.generic;

  const handleDownloadAll = () => {
    const allSchemas = schemas.map(s => s.schema);
    const blob = new Blob(
      [JSON.stringify(allSchemas, null, 2)],
      { type: 'application/json' }
    );
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'aeo-schemas.json';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadHTML = () => {
    const scriptTags = schemas
      .map(s => `<script type="application/ld+json">\n${JSON.stringify(s.schema, null, 2)}\n</script>`)
      .join('\n\n');

    const html = `<!-- AEO Schema Markup generated by AEO Schema Generator -->\n<!-- Add these tags to your <head> section -->\n\n${scriptTags}`;
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'aeo-schemas.html';
    a.click();
    URL.revokeObjectURL(url);
  };

  const shortUrl = (() => {
    try {
      const u = new URL(meta.canonicalUrl || '');
      return u.hostname + (u.pathname !== '/' ? u.pathname : '');
    } catch { return meta.canonicalUrl; }
  })();

  return (
    <section className="results-section" aria-label="AEO Analysis Results">
      {/* Results header */}
      <div className="results-header">
        <div>
          <h2 className="results-title">Analysis Complete</h2>
          <div style={{ display: 'flex', gap: '8px', marginTop: '8px', flexWrap: 'wrap' }}>
            <span className="results-url-tag" title={meta.canonicalUrl}>
              <Link size={12} />
              {shortUrl}
            </span>
            <span className="results-url-tag">
              {pageTypeInfo.emoji} {pageTypeInfo.label}
            </span>
          </div>
        </div>

        <div className="results-actions">
          <button
            id="reset-btn"
            className="btn-secondary"
            onClick={onReset}
            aria-label="Analyze another URL"
          >
            <RefreshCw size={14} />
            New Analysis
          </button>
          <button
            id="download-html-btn"
            className="btn-secondary"
            onClick={handleDownloadHTML}
            aria-label="Download schemas as HTML script tags"
          >
            <Download size={14} />
            Download HTML
          </button>
          <button
            id="download-json-btn"
            className="btn-primary"
            onClick={handleDownloadAll}
            aria-label="Download all schemas as JSON"
          >
            <Download size={14} />
            Download JSON
          </button>
        </div>
      </div>

      {/* AEO Score */}
      <AEOScoreCard score={score} />

      <div className="section-divider" />

      {/* Schema Cards */}
      <div className="schemas-section">
        <div className="schemas-header">
          <h3 className="schemas-title">
            Generated Schemas
            <span className="schemas-count-badge">{schemas.length}</span>
          </h3>
        </div>

        {schemas.map((schema, i) => (
          <SchemaCard
            key={schema.type}
            schemaResult={schema}
            index={i}
          />
        ))}
      </div>

      {/* Tips / Quick Wins */}
      {score.percentage < 60 && (
        <div className="quick-wins-section">
          <h4 className="quick-wins-title">
            💡 Quick Wins to Improve Your AEO Score
          </h4>
          <ul className="quick-wins-list">
            {score.metrics.filter(m => m.status === 'fail').map(m => (
              <li key={m.id}>
                <strong className="quick-wins-item-name">{m.name}</strong> — {m.detail}
              </li>
            ))}
          </ul>
        </div>
      )}
    </section>
  );
}
